// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qboobvzuylscjlxqtnfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFib29idnp1eWxzY2pseHF0bmZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDk5MzIsImV4cCI6MjA3MDYyNTkzMn0.w49iZ-Vk01u2Zwn3b-xK7cqJ0IOAfQlnahQ1KbitBpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});